services:
  mysql:
    image: mysql:8
    container_name: camagru-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: camagru
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    build: ./php
    container_name: camagru-php
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data: